$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - .git
  - bun.lockb
  - ./branch_out
  - .changeset
  - drizzle
  - '**/*.svg'
words:
  - acst
  - aest
  - akst
  - Anson
  - antlr
  - apos
  - aren
  - astro
  - astrojs
  - atrule
  - autodocs
  - autoplay
  - awst
  - Beamer
  - Binni
  - branchname
  - buildit
  - bunx
  - bvaughn
  - Byrom
  - callees
  - catchline
  - cjsx
  - classname
  - clsx
  - cmdk
  - codespace
  - codespaces
  - Colm
  - colour
  - colours
  - Combobox
  - commitlint
  - commitlintrc
  - compat
  - consts
  - cooldown
  - crossorigin
  - ctsx
  - datetime
  - dbaeumer
  - degit
  - didn
  - dotenv
  - draggables
  - dsznajder
  - Duarte
  - Elsakaan
  - Embla
  - esbenp
  - eslintcache
  - excalidraw
  - fontsource
  - fullname
  - googleusercontent
  - hookform
  - hyperscript
  - ianvs
  - Invisibles
  - ixahmedxi
  - jiti
  - johndoe
  - jscoverage
  - jspm
  - kohler
  - libsql
  - lockb
  - lucide
  - magicui
  - Malyavko
  - microbundle
  - mikestead
  - minimise
  - Mintlify
  - mjsx
  - monorepoing
  - mtsx
  - Navigations
  - neonctl
  - neondatabase
  - nextjs
  - noopener
  - noreferrer
  - nuxt
  - nzst
  - onwarn
  - optimisations
  - orbitkit
  - Ornella
  - packagejson
  - pacocoursey
  - pageview
  - peduarte
  - pids
  - Pilcrow
  - posthog
  - prismjs
  - protobuf
  - quickstart
  - Rajdeep
  - Ratelimit
  - Repobeats
  - Roboto
  - shadcn
  - signup
  - sindresorhus
  - sslmode
  - starterkit
  - starterkits
  - stylelint
  - stylelintcache
  - stylesheet
  - superjson
  - tada
  - tailwindcss
  - tamasfe
  - tanstack
  - thollander
  - todos
  - topbar
  - transpiles
  - treeshake
  - trpc
  - tsbuildinfo
  - tsconfigs
  - tseslint
  - tsup
  - Tuite
  - turborepo
  - turso
  - tursodatabase
  - typecheck
  - typeof
  - typesafe
  - udecode
  - unauthed
  - Ungroup
  - unifiedjs
  - unkey
  - uploadthing
  - vaul
  - vercel
  - viewports
  - vuepress
  - waitlist
  - WITA
  - wscript
  - yoav
  - zustand
  - COBE
  - cobe
