import { CaretSortIcon } from "@radix-ui/react-icons";
import {
  CheckIcon,
  ChevronDown,
  ChevronLeft,
  CircleDotDashed,
  Clipboard,
  Copy,
  GripVertical,
  Heading1,
  Heading2,
  Heading3,
  HelpCircle,
  Inbox,
  Maximize2,
  Minimize2,
  MoreHorizontal,
  PenBox,
  Plus,
  RemoveFormatting,
  Search,
  Trash,
  Trash2,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  search: Search,
  inbox: Inbox,
  issues: CircleDotDashed,
  newIssue: PenBox,
  info: HelpCircle,
  maximize: Maximize2,
  minimize: Minimize2,
  caretSortIcon: CaretSortIcon,
  checkIcon: CheckIcon,
  horizontalMore: MoreHorizontal,
  trash: Trash,
  heading1: Heading1,
  heading2: Heading2,
  heading3: Heading3,
  plus: Plus,
  gripVertical: GripVertical,
  removeFormatting: RemoveFormatting,
  clipBoard: Clipboard,
  copy: Copy,
  trash2: Trash2,
};
