import { CaretSortIcon } from "@radix-ui/react-icons";
import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircleIcon,
  ArrowUpDown,
  Bold,
  Book,
  BookOpenText,
  CheckCircle2,
  CheckIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  CircleDotDashed,
  Clipboard,
  Code,
  Code2,
  Copy,
  Dot,
  ExternalLink,
  Filter,
  Github,
  GripVertical,
  Heading1,
  Heading2,
  Heading3,
  HelpCircle,
  Hexagon,
  Highlighter,
  Home,
  Inbox,
  Italic,
  LayoutList,
  ListFilter,
  Loader2,
  Lock,
  LogOut,
  Maximize2,
  Minimize2,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Palette,
  PanelRight,
  PanelTop,
  PenBox,
  PenLine,
  Plus,
  RemoveFormatting,
  Rows3,
  Search,
  Settings,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SlidersHorizontal,
  SquarePen,
  SquareUserRound,
  Strikethrough,
  Subscript,
  Superscript,
  Tag,
  Trash,
  Trash2,
  Underline,
  User2,
  Users,
  X,
  XCircle,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  search: Search,
  inbox: Inbox,
  issues: CircleDotDashed,
  newIssue: PenBox,
  info: HelpCircle,
  maximize: Maximize2,
  minimize: Minimize2,
  caretSortIcon: CaretSortIcon,
  checkIcon: CheckIcon,
  horizontalMore: MoreHorizontal,
  trash: Trash,
  heading1: Heading1,
  heading2: Heading2,
  heading3: Heading3,
  plus: Plus,
  gripVertical: GripVertical,
  removeFormatting: RemoveFormatting,
  clipBoard: Clipboard,
  copy: Copy,
  trash2: Trash2,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  code: Code,
  code2: Code2,
  highlighter: Highlighter,
  palette: Palette,
  moreVertical: MoreVertical,
  subscript: Subscript,
  superscript: Superscript,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  alignJustify: AlignJustify,
  projects: LayoutList,
  github: Github,
  book: Book,
  settings: Settings,
  externalLink: ExternalLink,
  home: Home,
  back: ArrowLeft,
  lock: Lock,
  users: Users,
  listFilter: ListFilter,
  loading: Loader2,
  arrowRight: ArrowRight,
  dot: Dot,
  hexagon: Hexagon,
  team: SquareUserRound,
  user: User2,
  panelRight: PanelRight,
  filter: Filter,
  sliders: SlidersHorizontal,
  logOut: LogOut,
  squarePen: SquarePen,
  status: CircleDashed,
  signalHigh: SignalHigh,
  signalMedium: SignalMedium,
  signalLow: SignalLow,
  triangleAlert: AlertTriangle,
  minus: Minus,
  tag: Tag,
  backlog: CircleDashed,
  todo: Circle,
  inProgress: ArrowUpCircleIcon,
  done: CheckCircle2,
  canceled: XCircle,
  chevronRight: ChevronRight,
  panelTop: PanelTop,
  penLine: PenLine,
  bookOpenText: BookOpenText,
  rows3: Rows3,
  arrowUpDown: ArrowUpDown,
  x: X,
};
