name: Clean up after after a PR is closed or merged
run-name: Clean up PR database
on:
  pull_request:
    types: [closed]

jobs:
  delete-db-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

      # Delete the branch from the Turso database
      - name: Delete Turso DB
        shell: bash
        run: |
          RESPONSE=$(curl -L -X DELETE 'https://api.turso.tech/v1/organizations/{organizationName}/databases/{databaseName}' \
            -H 'Authorization: Bearer ${{secrets.TURSO_API_TOKEN}}')

          if [ $? -ne 0 ]; then
            echo "API call failed"
            exit 1
          fi
