name: Pull Request CI

on: [pull_request]

env:
  # This enables turborepo's remote task caching
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  spell-and-md-lint:
    name: Spellcheck and Markdown Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Checks
        run: bun turbo lint:md lint:spell

  web:
    name: Web
    runs-on: ubuntu-latest

    env:
      # Database
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}

      # Auth Secret
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

      # Github OAuth
      AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
      AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}

      # Google OAuth
      AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
      AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

      - name: Setup
        uses: ./.github/actions/setup

      - name: Checks
        run: bun turbo lint typecheck build test:e2e --filter=@buildit/web

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-playwright-report
          path: apps/web/playwright-report/
          retention-days: 30
