name: Pull Request CI

on: [pull_request]

env:
  # This enables turborepo's remote task caching
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  spell-and-md-lint:
    name: Spellcheck and Markdown Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Checks
        run: bun turbo lint:md lint:spell
